### ISSUE TITLE
Add support for new document collection API

### ISSUE THREAD

**Issue by nadre** [averbis/averbis-python-api#12]
**Is your feature request related to a problem? Please describe.**
It would be useful to support the new api.

**Describe the solution you'd like**
Add crud methods to the Project class and introduce a new DocumentCollection class.
Add crud methods to the DocumentCollection class.

**Comment by DavidHuebner** [comment]
Hi @nadre - I would continue with this issue. I will implement the following five endpoints:
![image](https://user-images.githubusercontent.com/14200897/110329344-bcce2c00-801c-11eb-94c6-c7f6ce8cf3d5.png)

**Comment by DavidHuebner** [comment]
Ready to be reviewed.

**Comment by DavidHuebner** [comment]
**Exemplary usage:**
``` python 
    client = Client(url)
    project = client.get_project("my_project")
    collection = project.create_document_collection("my_collection")

    file_path = "resources/texts/text1.txt"
    with open(file_path, "r", encoding="UTF-8") as input_io:
        collection.import_documents(input_io)
    print(f"Number of documents: {collection.get_number_of_documents()}")
    collection.delete()
```
