### ISSUE TITLE
Current tests are failing due to the usage of relative directories

### ISSUE THREAD

**Issue by DavidHuebner** [averbis/averbis-python-api#15]
**Describe the bug**
Currently, a few of the tests are failing because they use absolute paths.

**To Reproduce**
1. Open the project in PyCharm
2. Run all tests

If possible, attach a minimal file that triggers the error. 

**Expected behavior**
Tests should run.

**Error message**
`FileNotFoundError: [Errno 2] No such file or directory: 'tests/resources/settings/client-settings.json'`

**Please complete the following information:**
 - Version: 0.2.0dev
 - OS: Ubuntu 20.04

**Comment by reckart** [comment]
You have to run the Tests from the root. Tell pycharm to do that then it works.

**Comment by DavidHuebner** [comment]
Yeah, I think that is should just work without the need for any additional test settings. I created a pull request here #16 .
