### ISSUE TITLE
Move management of processes to document collection level

### ISSUE THREAD

**Issue by reckart** [averbis/averbis-python-api#54]
**Describe the refactoring action**
Currently, methods for managing processes are exposed at the level of the project. However, processes are bound tightly to document collections, so it may be better to move the methods there.

**Expected benefit**
Facilitate APi for the user e.g. os that an info such das the document collection name does not need to be specified multiple times:
* user creates a project -> gets a Project object
* user creates a document collection in the project -> gets a DocumentCollection object
* user creates a process on that document collection -> gets a Process object
* user fetches the results of the process -> gets e.g. a CAS or JSON object

**Comment by DavidHuebner** [comment]
As part of the ticket, I want to add a proper String representation of our objects (Client, Pipeline, Process, etc.). Right now, if we call 
print(Pipeline), we get something like: `<averbis.core._rest_client.Pipeline object at 0x7f91657b7400>`

Instead, I would like to have the output `Pipeline(name="Discharge", project="test")`. This can be archieved using the __repr__ method for each class.
