### ISSUE TITLE
Allow setting the request timeout

### ISSUE THREAD

**Issue by chgl** [averbis/averbis-python-api#62]
**Is your feature request related to a problem? Please describe.**

It would be helpful to increase the request timeout, especially when processing large texts.

**Describe the solution you'd like**

When initializing the AHD Client, it should be possible to pass an argument serting the http request timeout.

**Describe alternatives you've considered**

None.

**Additional context**

I believe passing the timeout value to `requests.request` in https://github.com/averbis/averbis-python-api/blob/main/averbis/core/_rest_client.py#L845 would be a viable solution (see also https://docs.python-requests.org/en/master/user/quickstart/#timeouts).

Thank you for this helpful and well-designed library!

**Comment by reckart** [comment]
Thanks for the report. We'll look into it.

**Comment by chgl** [comment]
Thank you! In retrospective, I think it might make more sense to set the timeout per-request, so as a parameter of `analyse_text/html()` to support retry mechanisms such as exponential backoff.

**Comment by DavidHuebner** [comment]
Thanks for your request @chgl . We have discussed the issue internally. We will basically realize both of your suggestions, a global timeout on Client level and a local timeout parameter for some dedicated endpoints (`analyse_text`, `analyse_texts`, `analyse_html`, `analyse_text_to_cas`, `classify_text`). If both are set, the local one prevails.

I will create a merge request, and hopefully we can release version 0.4.0 by next week.

**Comment by chgl** [comment]
Sounds perfect, thank you very much!

**Comment by DavidHuebner** [comment]
Merge request is ready to be reviewed (https://github.com/averbis/averbis-python-api/pull/77)
