### ISSUE TITLE
Experimental support for obtaining an analysed text as a UIMA CAS

### ISSUE THREAD

**Issue by reckart** [averbis/averbis-python-api#9]
**Is your feature request related to a problem? Please describe.**
For certain use-cases, it would be helpful if one could work directly on the UIMA CAS data produced by a pipeline.

**Describe the solution you'd like**
If there is a REST endpoint which supports obtaining a pipeline result as an UIMA CAS object (e.g. XMI), then it would be nice if the Python API supported that, possibly directly calling DKPro Cassis to parse the CAS object into a nice Python representation and returning that from the endpoint invocation to the caller code.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by DavidHuebner** [comment]
The next major version of our Health Discovery & Information Discovery will have an experimental endpoint for obtaining the result of a text analysis as a UIMA CAS object and for obtaining the currently used TypeSystem. With that, the functionality on this branch is already used in preliminary tests and we should start thinking about merging this branch back. Is there something still missing for that?
